on:
  push:
    branches:
      - main

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: .
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: deleteme-reactdemo2
        package: .\build
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}